name: Build & Analyze with Microwalk

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  script_directory: microwalk

jobs:
  build-analyze:
    
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Microwalk analysis
        id: run_microwalk
        uses: microwalk-project/microwalk-pin-action@v1
        with:
          script-directory: ${{ env.script_directory }}
      
      - name: Upload analysis result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/${{ env.script_directory }}/results/report-target-loop-leakage.sarif
          checkout_path: ${{ github.workspace }}
      
      - name: Archive analysis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: leakage-analysis-results
          path: ${{ github.workspace }}/${{ env.script_directory }}/results
